### ISSUE TITLE
[Bug] SerdeErr: pointer not found

### ISSUE THREAD

**Issue by dongdigua** [kingwingfly/fav#127]
**Describe the bug**

**To Reproduce**
```
fav pull
```
or
```
fav daemon
```
it shows:
```
 INFO Fetching sets...
 INFO Fetch sets successfully.
 INFO Fetch archives sets successfully.
 INFO Fetching set<...>
ERROR SerdeErr: pointer not found
```

**Information (please complete the following information):**
Arch Linux
```
[~]─── fav --version
fav_cli v0.2.32
RUSTC: x86_64-unknown-linux-gnu stable 1.80.1
```

**Comment by kingwingfly** [comment]
Did it panic (crash)? Or it just prints a message?

**Comment by kingwingfly** [comment]
我觉得我这儿应该没问题。
如果只有一个`serde pointer not found`的话，只有可能是Wbi鉴权那里有点小错，应该是阿B没有返回正确的结果，感觉重新运行一次就可以了。

tips：错误信息是输出到标准输出的，你可以把错误信息重定向到文件，避免进度条影响观察。

**Comment by dongdigua** [comment]
> Did it panic (crash)? Or it just prints a message?

crash

**Comment by kingwingfly** [comment]
你可以试一下新的 v0.2.34 ，那个版本基本没有panic的可能。

你用的v0.2.32版本，我就不排查了。
