### ISSUE TITLE
[Bug]初始化的路径不符合预期

### ISSUE THREAD

**Issue by feiudfyg** [kingwingfly/fav#15]
**Describe the bug**
fav.exe似乎使用了由命令行传递的路径作为工作路径，而不是它实际处于的文件夹。

**To Reproduce**
1.将fav.exe移动至一文件夹
2.将该文件夹的完整路径添加至系统环境变量"PATH"中
3.以管理员权限启动powershell，观察到当前的工作目录为”C:\Windows\System32“
4.输入“fav init” .观察到命令行界面出现了fav.exe的响应
5.输入"fav auth login"并按照正确方式登录
6.在资源管理器中打开”C:\Windows\System32“，在其中发现了".fav"文件夹，内有存有用户id等信息的文件“bili”，创建时间戳相符
   表明fav.exe初始化时选用了命令行提供的路径作为工作路径，而不是它实际处于的文件夹。

这对于使用“PATH”环境变量以缩短命令长度的用户并不友好，每次都要定位到同一文件夹来调用，否则就需要重新初始化

**Expected behavior**
fav.exe以它实际处于的文件夹作为初始化路径，而不是简单地从命令行接受工作路径

**Screenshots**
无

**Information (please complete the following information):**
OS: Windows 11 22621.1702
Output of `rustc -V`
我使用了预构建版本，并没有自行从仓库构建。

**Additional context**
建议默认使用fav.exe实际的文件位置作为工作路径，或允许在init后提供参数来手动选择路径

**Comment by kingwingfly** [comment]
建议在工作目录 shift + 右键，可以在该目录打开 powershell。

环境变量的作用是让用户可以在任何目录通过 `fav` 直接调用，而不需要完整的路径。

一般所有的命令行工具都是工作在当前目录上的，比如git，kubectl，docker等等。

**Comment by feiudfyg** [comment]
> 建议在工作目录 shift + 右键，可以在该目录打开 powershell。
> 
> 环境变量的作用是让用户可以在任何目录通过 `fav` 直接调用，而不需要完整的路径。
> 
> 一般所有的命令行工具都是工作在当前目录上的，比如git，kubectl，docker等等。

那不是有点麻烦嘛。为什么不在init后面加个参数允许用户手动输入初始化路径？
并且也不是所有用户都考虑得那么全面 可能像我那样时不时想起来就直接打个fav pull，不会每次都想到要打开到文件夹再右键“”此处打开powershell“或者预先cd过去

**Comment by kingwingfly** [comment]
你可以使用 `fav daemon 120`

这个命令会每120分钟pull一次

**Comment by feiudfyg** [comment]
我确实已经设置了定时pull。
请问如果因为关机导致过了定时没能运行 是会在开机后立即运行吗？
它不会要保持后台运行吧 那我还得加个服务

**Comment by kingwingfly** [comment]
不会，重启后依然需要重新运行这个命令。

我不熟悉Linux，daemon这个名字只是借用，其实叫cron更好，但是cron相对比较冷门。

**Comment by feiudfyg** [comment]
刚刚看了一下后台还真的没守护进程
能不能考虑设置个开机启动项，写个配置文件记录上次pull的时间和间隔...不然真的要挂在服务器这种地方了
感觉一般人都不会有台24小时在线的机子

**Comment by kingwingfly** [comment]
开机自动任务应该是操作系统的工作，可以查询一下自己的操作系统如何设置自动任务。

**Comment by feiudfyg** [comment]
明白了。其实用计划任务也可以替代daemon命令的工作，是我考虑不周。

**Comment by kingwingfly** [comment]
v0.2.35 新增 `-d` 参数用于指定工作目录。
