### ISSUE TITLE
[New Feature] pull时跳过已经下载过且存在于目录的视频不下载

### ISSUE THREAD

**Issue by feiudfyg** [kingwingfly/fav#16]
**Is your feature request related to a problem? Please describe.**
每次pull都会把已经下载过的文件重新下载覆盖一遍。

**Describe the solution you'd like**
运行pull命令后应当先检测目录下是否有相同视频。有则跳过，否则下载。
为了防止视频同名不同bvid，建议下载的文件命名时在文件名尾部加入bvid。

**Describe alternatives you've considered**
没想到别的方法了。

**Additional context**
真的希望解决 不然频繁下载可能导致账号异常

**Comment by kingwingfly** [comment]
如果直接 pull 那个收藏夹id，就会强制下载；pull后面不跟参数，就是pull all。
这是由于当用户误删了某个视频，需要重新下载时，由于视频的已经被标记成了已下载，就无法重新下载了。于是提供pull视频的bvid以强制下载的功能。

我的流程是这样的，供参考：
```
fav init
fav auth login
fav fetch
fav track xxx
fav pull
#如果需要每两个小时同步一次：
fav daemon 120
```

关于重名视频覆盖的问题，见#13，预计在下个版本（v0.2.2）修复。

**Comment by feiudfyg** [comment]
那么pull不加参数就会跳过相同视频是吧？感谢采纳!

**Comment by kingwingfly** [comment]
会的，我已经修改了这个命令的help信息。

**Comment by feiudfyg** [comment]
行为变得好怪异啊 现在它仍然在下载已经下载过的文件并且往%temp%疯狂写入
但是存文件的文件夹里面文件的时间戳没有更新，也没观察到复制文件过去的行为。是全部下载完再删掉多余的吗？
![屏幕截图 2024-02-24 170723](https://github.com/kingwingfly/fav/assets/107339377/8f62d2ca-bd30-4a20-a5e6-7292ba1da50f)

**Comment by kingwingfly** [comment]
可能是因为你之前遇到bug了，没有完整成功过。

资源状态是完整下载了一个收藏夹之后保存的，而不是每下载一个视频保存的。

比如，你下载ABCD四个视频，但是下载完B之后，崩溃了。再次下载的时候，又会重新开始下载。

**Comment by feiudfyg** [comment]
明白了

**Comment by kingwingfly** [comment]
再补充一点：手动 ctrl-c 是实现了优雅退出的。使用 ctrl-c 终止，会把已经下好的视频标记成已下载。
