### ISSUE TITLE
[Bug] Crashed while downloading

### ISSUE THREAD

**Issue by feiudfyg** [kingwingfly/fav#17]
**Describe the bug**
它在我下载大量视频的时候崩溃并输出了报错信息。

**To Reproduce**
正常使用，并pull。
下载时输出

thread 'main' panicked at D:\a\fav\fav\fav_utils\src\bili\ops.rs:153:41:
called `Option::unwrap()` on a `None` value
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Expected behavior**
正常下载完所有视频

**Screenshots**

![屏幕截图 2024-02-24 150146](https://github.com/kingwingfly/fav/assets/107339377/fbf391cf-bbcc-45ab-b8c6-c167412fea94)

**Information (please complete the following information):**
OS: Windows11 22621.1702
Output of `rustc -V`
我使用了预构建版本，并没有rust环境。

**Additional context**
无

**Comment by kingwingfly** [comment]
这确实是我这儿错误处理有点草率了。

这是由于正要下载的那个视频没有base_url。我可能需要在v0.2.3版本中，输出出错的资源的id，我认为出现这个问题，要么是由于请求的资源不是视频，要么是访问过多，被拒绝了。但是我这儿自己一次性下载大量的视频没有问题，暂时怀疑第一种可能。

**Comment by feiudfyg** [comment]
出错的资源建议跳过然后在运行完毕后显示id 直接崩溃给我整懵了

**Comment by kingwingfly** [comment]
我这儿稍微修改了，你可以在你的收藏夹那儿截个图吗，我需要了解一下具体是那个资源不支持，写个测试。

Edit：大概就是后面的最近那个还没有开始下载的视频

**Comment by feiudfyg** [comment]
![屏幕截图 2024-02-24 162653](https://github.com/kingwingfly/fav/assets/107339377/f97736f4-264a-45a3-8aad-a69e673886e5)

**Comment by feiudfyg** [comment]
一大堆并行下载的时候可能因为文件大小不同导致最后变成小的先下载完大的还没有
最后就渐渐没顺序了
按这样看好像不好找
而且我有三个收藏夹在下载...
对了三次崩溃都是一模一样的位置 输出也一样 说不定可以再试一遍

**Comment by kingwingfly** [comment]
悲！看不出来是那个视频的问题。。。

另，当前对于合集视频，只会下载合集中第一个，因为收藏一个视频会收藏整个合集，下载整个合集是不符合预期的。

**Comment by feiudfyg** [comment]
> 另，当前对于合集视频，只会下载合集中第一个，因为收藏一个视频会收藏整个合集，下载整个合集是不符合预期的。

合集没事，我不在意
哪个视频我也不知道啊(悲
我想到几种可能：1.被锁了要充电才能看的 
2.远古上传为视频结果被b站收编成官方番剧的 
3.失效了但是没有完全失效处于量子叠加态的（比如打开之后显示肥肠抱歉油库里音效）那种用别的工具也不能下载

**Comment by kingwingfly** [comment]
建议利用bilibili app端的收藏夹管理功能，把真正需要下载的视频移动到某个单独的文件夹来暂时解决这个问题。

**Comment by feiudfyg** [comment]
明白。
愿bug能尽早修复

**Comment by kingwingfly** [comment]
新发布的 v0.2.3 可以试一下。如果不行，那就暂时没办法排查了，除非知道具体是那个资源。

**Comment by feiudfyg** [comment]
我试试

**Comment by feiudfyg** [comment]
很大可能已经修复了。在刚刚的测试中没有出现错误。
