### ISSUE TITLE
[Bug] `fav pull` downloads nothing even though `fav status -r -t` shows the resources as tracked but not saved

### ISSUE THREAD

**Issue by ZhangTianrong** [kingwingfly/fav#18]
**Describe the bug**
`fav pull` ends after successfully fetching the set without downloading anything. This happened to 3 of my 4 sets.

**To Reproduce**
Steps to reproduce the behavior, or a Minimal Reproducible Code Snippet.
```
fav init
fav auth login
fav status -s # to find the set id
fav track <set_id>
fav fetch
fav pull
```

**Expected behavior**
`fav pull` downloads the files correctly and if there is an error encountered when downloading a resource, log it somewhere.

**Screenshots**
![PixPin_2024-02-28_16-50-33](https://github.com/kingwingfly/fav/assets/20651728/d7955586-18ac-4de8-9961-e9f4afc244bd)

**Information (please complete the following information):**
OS: TrueNAS Scale Cobia
Output of `rustc -V`: N/A, didn't compile `fav` from scratch

**Additional context**
None

**Comment by kingwingfly** [comment]
Could you please show me the result of `fav status -st`? I wonder how you tracked the sets to locate the bug. 

I notice that you said 4 sets are tracked, but the result of `fav fetch` shows only 1 set was fetched.

**Comment by ZhangTianrong** [comment]
> fav status -st

That's because `fav` doesn't preserve directory structure, so I have to create one directory for each set.

![PixPin_2024-02-28_23-25-50](https://github.com/kingwingfly/fav/assets/20651728/b3646410-541a-4465-8c5d-6b8505de6cea)

A bit of digression, but isn't there a switch to turn on verbose logging? In the set which `fav pull` does work, it doesn't warn me of resources that it fails to download.

![PixPin_2024-02-28_23-32-16](https://github.com/kingwingfly/fav/assets/20651728/860b1223-583a-4c96-be3c-f40289d54677)

**Comment by kingwingfly** [comment]
I tried my best, but I still cannot reproduce this bug.
```sh
 ~/Downloads  mkdir 1                                                                           Thu Feb 29 12:46:39 2024
 ~/Downloads  mkdir 2                                                                           Thu Feb 29 12:53:23 2024
 ~/Downloads  cd 1                                                                              Thu Feb 29 12:53:25 2024
 ~/D/1  ls                                                                                      Thu Feb 29 12:53:27 2024
 ~/D/1  fav init                                                                                Thu Feb 29 12:53:28 2024
 ~/D/1  fav auth login                                                                          Thu Feb 29 12:53:32 2024
 INFO Scan the QR code to login.

█████████████████████████████████████████████████████
█████████████████████████████████████████████████████
████ ▄▄▄▄▄ █▀█▄ ▄█ █▄█▀▀▄ ▄ ▀▀ ▄█▀▄▀▀ █▀▄█ ▄▄▄▄▄ ████
████ █   █ █ █▀█ ▄█▀ █ ████▀▄▄█  ▄ ▀  █ ▀█ █   █ ████
████ █▄▄▄█ ██▄▄ █▀█▄▄▀█▄ ▄▄▄  ▀█▀█▄███▄▄▄█ █▄▄▄█ ████
████▄▄▄▄▄▄▄█ █ ▀ ▀▄▀ █▄▀ █▄█ ▀ █ ▀ █ █▄▀ █▄▄▄▄▄▄▄████
████ █▀▀█▀▄█  ▀ ▄ ▄▄▄▄▀ ▄▄ ▄ ▀▀▀▀   █ ▀▀▀▄ ▀█   █████
█████ ▄▀ ▄▄▀▀██▀▄ ▄ █ ▀▄██ ▀ ▀ ▄ ▄▀▀ ▄▄▄▀▄▄ ▀▄ ▄█████
████▀  ▀ ▀▄██▄▄█▀███▀▄▄█▄ ▀█▀▄██ █ █ ▀█▀▀▄▄█▄ ▀▄█████
████ ▀▀██ ▄▄██▀  ▄  ▀▄▄█▄ ▄█▄█ ▀█▄▀██▀▄▄ ▀ █▄▀ ▀ ████
████▀██ ██▄█ █ ▄ █ █ ▄▄▄ ▄▀█▄█▀ ▀▀▀▄█▀▄ ▀▀▄ ██▀█▀████
████▄ ▄▄ █▄▄▄ ▀▀█▄▄▀  ▄ ██▄▀▄▄▄█ ▀█  ▄█▀███  █▀▀▄████
████▀▄██ ▄▄▄ █ ▀▄▀▄ █▀ ▀ ▄▄▄ ▀ ▀█ ▀▀█▀▀▀ ▄▄▄   ▀▄████
████ ▀▄█ █▄█ █▀  ▀█▄ ▀   █▄█ █ █▀███▀▄▄▄ █▄█ ▀ ██████
████  ▀█ ▄▄▄▄ ▀█▄▄██▄    ▄ ▄ ▀▄█ █ ▀ ▀▄▄ ▄▄ ▄▀█▄▀████
████▄█▀  ▀▄▄█▄ ▀▄ █▀ ▀▄▀ █▄▀▀▀▄▄█▄█ ▄█ ▀▄█ ▄▀  ▄█████
███████▄▄█▄ ██▀ ▄█▀ ▀▀▄█▀ ▀▄▄ ▄ ▀█  ▀▀▄▀ █ ▀▄▀▀▄▄████
████▀ ▄▀██▄  █▄▀▄  ▀▀▀▀▀ ▀██▀██ ▄▀▀▀▀▀█ ▄▄ ▄▄█  █████
████▀  █▄▄▄▀██▀ █▄ ▀ ▄█ ▀ █ ▄█▀▄▀█  █ ▀█  ▄▄▄▄██▄████
█████▀▀▀ █▄ ▄▄█▀▄▄▀█▀  ▄█ █▀▄▀ ▄▀▀█▀▀▄▄▀  ▀▄██▄▄█████
████▄██▄▄█▄█▀▀▀██ █▀  ▀▄ ▄▄▄ ▀█▀    ▄▀▄  ▄▄▄   ▄▀████
████ ▄▄▄▄▄ ██▄ ▄▀ █  █▄  █▄█ █ █▄▀█▀▀▄   █▄█ ▀  █████
████ █   █ ███▀ ▀███▀██▀ ▄▄▄ ▀▄█▀▄  █▀▄  ▄▄  ▄▀▄▄████
████ █▄▄▄█ ███▄▀▄█▄█  ▀█▀▀ ██▄█▀▀▀ █ ██▄ ▀▄ ▄▀ █▄████
████▄▄▄▄▄▄▄█▄█▄██▄▄█▄█▄▄█▄▄▄▄▄▄▄███▄█▄█▄▄▄▄█▄▄█▄█████
█████████████████████████████████████████████████████
▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀▀
 INFO Login successfully.
 ~/D/1  cd ..                                                                            9.3s  Thu Feb 29 12:54:02 2024
 ~/Downloads  cd 2                                                                              Thu Feb 29 12:54:07 2024
 ~/D/2  fav auth reuse ../1/.fav                                                                Thu Feb 29 12:54:08 2024
ERROR IOErr: No such file or directory (os error 2); Maybe you didn't run `fav init`
 ~/D/2  fav init                                                                                Thu Feb 29 12:54:17 2024
 ~/D/2  fav auth reuse ../1/.fav                                                                Thu Feb 29 12:54:27 2024
 ~/D/2  fav fetch                                                                               Thu Feb 29 12:54:29 2024
 INFO Fetching sets...
 INFO Fetch sets successfully.
 ~/D/2  fav status                                                                      250ms  Thu Feb 29 12:54:33 2024
 ~/D/2  fav status -s                                                                           Thu Feb 29 12:54:35 2024
┌────────────┬────────────┬───────┬───────┐
│ ID         │ Title      │ Count │ Track │
├────────────┼────────────┼───────┼───────┤
│ 57010888   │ 默认收藏夹 │ 510   │ false │
├────────────┼────────────┼───────┼───────┤
│ 2865558988 │ old        │ 658   │ false │
├────────────┼────────────┼───────┼───────┤
│ 2337063988 │ 星穹铁道   │ 8     │ false │
├────────────┼────────────┼───────┼───────┤
│ 2329351088 │ 1999       │ 1     │ false │
├────────────┼────────────┼───────┼───────┤
│ 1844042288 │ Rust       │ 9     │ false │
├────────────┼────────────┼───────┼───────┤
│ 1188059388 │ 原神       │ 213   │ false │
├────────────┼────────────┼───────┼───────┤
│ 158322788  │ favorite   │ 53    │ false │
├────────────┼────────────┼───────┼───────┤
│ 321866388  │ music      │ 110   │ false │
└────────────┴────────────┴───────┴───────┘
Count: 8

 ~/D/2  fav track 2329351088                                                                    Thu Feb 29 12:54:41 2024
 ~/D/2  fav pull                                                                                Thu Feb 29 12:54:50 2024
 INFO Fetching sets...
 INFO Fetch sets successfully.
 INFO Fetching set<2329351088>
 INFO Fetch set<2329351088> successfully.
【重返未来1 ⠒ [00:00:06] [##########>---------------------------------------------] 16.72 MiB/85.40 MiB (2.79 MiB/s, 25s)
 WARN Ctrl-C cancelled
 ~/D/2  cd ../1                                                                          7.4s  Thu Feb 29 12:55:02 2024
 ~/D/1  fav fetch && fav track 1844042288                                                       Thu Feb 29 12:55:07 2024
 INFO Fetching sets...
 INFO Fetch sets successfully.
 ~/D/1  fav pull                                                                        134ms  Thu Feb 29 12:55:38 2024
 INFO Fetching sets...
 INFO Fetch sets successfully.
 INFO Fetching set<1844042288>
 INFO Fetch set<1844042288> successfully.
从头实现Rust ⠉ [00:00:05] [>-------------------------------------------------------] 4.35 MiB/392.42 MiB (1.26 MiB/s, 5m)
Rust Axum  ⠈ [00:00:05] [>-------------------------------------------------------] 2.94 MiB/423.72 MiB (938.06 KiB/s, 8m)
使用 Rust 开发 ⠠ [00:00:04] [#>-------------------------------------------------] 670.79 KiB/23.64 MiB (177.06 KiB/s, 2m)
 ~/D/1  fav pull                                                                         7.3s  Thu Feb 29 12:55:49 2024
 INFO Fetching sets...
 INFO Fetch sets successfully.
 INFO Fetching set<1844042288>
 INFO Fetch set<1844042288> successfully.
Rust新手开发 ⠂ [00:00:04] [###>----------------------------------------------------] 2.67 MiB/47.69 MiB (1.09 MiB/s, 41s)
Rust新手开发 ⠂ [00:00:04] [###>----------------------------------------------------] 2.67 MiB/47.69 MiB (1.09 MiB/s, 41s)
Rust Async ⠤ [00:00:03] [>------------------------------------------------------] 606.79 KiB/65.49 MiB (243.43 KiB/s, 5m)
 ~/D/1  cd ../2                                                                          5.6s  Thu Feb 29 12:56:01 2024
 ~/D/2  fav pull                                                                                Thu Feb 29 12:56:07 2024
 INFO Fetching sets...
 INFO Fetch sets successfully.
 INFO Fetching set<2329351088>
 INFO Fetch set<2329351088> successfully.
【重返未来1 ⠴ [00:00:03] [#####>---------------------------------------------------] 8.69 MiB/85.40 MiB (2.85 MiB/s, 27s)
 WARN Ctrl-C cancelled
```
I add `fav auth reuse` just now, so there's no need to scan code multiple times.

**Comment by kingwingfly** [comment]
> A bit of digression, but isn't there a switch to turn on verbose logging? In the set which fav pull does work, it doesn't warn me of resources that it fails to download.

NO, there is no such a switch. But only expired resource will fail without any hint since its info became useless. Otherwise, network or auth errors will be showed.

**Comment by kingwingfly** [comment]
I just tested on my roommate's computer, all work well and no bug.

**Comment by ZhangTianrong** [comment]
> I add `fav auth reuse` just now, so there's no need to scan code multiple times.

![PixPin_2024-02-29_03-04-15](https://github.com/kingwingfly/fav/assets/20651728/3cd1367d-41fc-4ac0-b5ca-669012a5ca3f)

Doesn't seem to work.

![PixPin_2024-02-29_03-09-31](https://github.com/kingwingfly/fav/assets/20651728/a6878695-e279-4c23-bafb-de9bd3ec5f4e)

In fact, the new release cannot even login and list the sets properly.

**Comment by kingwingfly** [comment]
end with .fav.
You can find the example with `fav auth reuse -h`

**Comment by kingwingfly** [comment]
And your second picture even did not fetch first.

**Comment by ZhangTianrong** [comment]
> And your first picture even did not fetch first.

My bad. The sets do show up after fetching first. This set pulls correctly as well.

> end with .fav. You can find the example with `fav auth reuse -h`

However, even with `.fav` appended to the end, I still cannot reuse the authentication from another directory. The error is different though.

![IMG_9830](https://github.com/kingwingfly/fav/assets/20651728/2f03da3b-f57c-46e4-abe5-a8ee4a16d139)

I will test the other two sets later. If they also pull correctly, I will close this issue. If the problem with `reuse` persist, I will open a separate issue for it.

**Comment by kingwingfly** [comment]
`fav auth reuse` actually equals to `cp ../Fitness/.fav/bili .fav/bili`, you can easily run this instead. 

I guess you don't have enough permission to do this job, and this may lead to unexpected behavior when using `fav`.

May be you could run with `sudo` or use `chmod +rw xxx` to enable write and read permission.

**Comment by kingwingfly** [comment]
I reproduced `Operation not permitted` on arch Linux just mow. 

This is leading by mounting filesystem with `sudo`, the owner of the files is root.

You should mount your disk with `udisksctl` instead, other method [here](https://unix.stackexchange.com/a/96643). 

Anyway, just ensure you have the permission to modify files under `.fav`.

**Comment by kingwingfly** [comment]
I reproduced `Operation not permitted` on arch Linux just now. 

This is leading by mounting filesystem with `sudo`, the owner of the files is root.

You should mount your disk with `udisksctl` instead, other methods are  [here](https://unix.stackexchange.com/a/96643). 

Anyway, just ensure you have the permission to modify files under `.fav`.

**Comment by ZhangTianrong** [comment]
> I reproduced `Operation not permitted` on arch Linux just now.
> 
> This is leading by mounting filesystem with `sudo`, the owner of the files is root.
> 
> You should mount your disk with `udisksctl` instead, other methods are [here](https://unix.stackexchange.com/a/96643).
> 
> Anyway, just ensure you have the permission to modify files under `.fav`.

![PixPin_2024-03-03_17-29-10](https://github.com/kingwingfly/fav/assets/20651728/28652242-fe8a-48a3-80fc-6134f14871ab)

**Comment by kingwingfly** [comment]
那属实是不知道咋回事了
![image](https://github.com/kingwingfly/fav/assets/38573173/e699edb8-3c4e-4ec2-9bcf-3ca1b5e13cbe)

**Comment by kingwingfly** [comment]
我试一下把复制改成链接
