### ISSUE TITLE
[Bug] NetworkErr when pull video

### ISSUE THREAD

**Issue by Weidows** [kingwingfly/fav#22]
**Describe the bug**
在 pull 某个视频时, 必然会error

**To Reproduce**
这个视频:
https://www.bilibili.com/video/BV1jz4y1S7PU/

**Screenshots**
![image](https://github.com/kingwingfly/fav/assets/61131704/1e16a504-372a-468b-802d-bac65416e4c4)

**Information (please complete the following information):**
OS: Win11

**Additional context**
pull 了 300 多个, 遇到了几个 error, 其他的重新 pull 一下就都可以了, 但只有这个一直不行
没走代理, 浏览器是可以看的

**Comment by kingwingfly** [comment]
我刚试了，没有问题。你可以现在再试试，我怀疑是你pull的时候，这个视频的B站服务碰巧不可用。

**Comment by Weidows** [comment]
> 我刚试了，没有问题。你可以现在再试试，我怀疑是你pull的时候，这个视频的B站服务碰巧不可用。

还真是可以了, 奇怪的问题
thanks❤
