### ISSUE TITLE
[Help] fav command not found after cargo build --release on Mac

### ISSUE THREAD

**Issue by Zion-Go** [kingwingfly/fav#53]
Hi, 

Thank you very much for your work. I have an issue: After I followed the README till cargo build --release on Mac, fav command couldn't be found. Maybe it is the problem of ENV or something else.
Could you give a hint how we can set ENV or the true solutions?

Thank you!

**Comment by kingwingfly** [comment]
For Mac users, just run
```
mv target/release/fav /usr/local/bin
```
Since Mac has `/usr/local/bin` in path by default, and we usually put self-developped software in it.

If you are not familiar with Rust, downloading binary in release page is just OK, you may not need to compile by yourself.

**Comment by kingwingfly** [comment]
Moreover, [this](https://doc.rust-lang.org/cargo/commands/cargo-install.html) may be a more Rusty way.

```
cargo install --path .
```

I saw it somewhere I forgot, but this may work.

**Comment by Zion-Go** [comment]
Thank you! Now it works.
Via your advice: 
mv fav/ to /usr/local/bin/ 
cargo install --path ./fav
work for me.
