### ISSUE TITLE
[New Feature] Add init comand confirmation

### ISSUE THREAD

**Issue by feiudfyg** [kingwingfly/fav#74]
**Is your feature request related to a problem? Please describe.**
手残输了init 成功失去所有历史记录 pull之后全部重新下了一遍 对磁盘造成了重创

**Describe the solution you'd like**
init命令运行后需要输入yes二次确认才会继续执行，输入no则取消执行。
类似这样

Would you like to reset all program-related files and initialize? input YES to proceed, NO to cancel.
Your choice:

**Describe alternatives you've considered**
没有什么比这更好的方法了吧

**Additional context**
我觉得init这玩意跟rm -rf一个性质，都会移除很重要的数据，因此一个二次确认是必须的。

**Comment by kingwingfly** [comment]
中嘞，明天改。我是下载后直接上传的 OneDrive，然后 OneDrive 给我的 .fav 维护了历史版本。

**Comment by kingwingfly** [comment]
Enhanced in `v0.2.18`, so kind if you could test it. If no bug found in this week, I'll close this issue.

**Comment by feiudfyg** [comment]
i will test it later and reply here.

**Comment by feiudfyg** [comment]
I tested it for 3 times, it works well. I will close this issue.
