### ISSUE TITLE
[Bug] Program CRASHES randomly after performing “fav pull"

### ISSUE THREAD

**Issue by feiudfyg** [kingwingfly/fav#75]
**Describe the bug**
随机崩溃，表现为执行pull后在任意时间经过后可能出现崩溃。

**To Reproduce**
无法预料的崩溃，因此无法完美复现。

可能的复现方法：
0. delete .fav\sets and re-register all sets
1. perform "fav pull"
2. wait for crash
    if no crash:
        goto 0

**Expected behavior**
程序在执行"fav pull" 后正常下载所有文件并退出

**Screenshots**
![屏幕截图 2024-06-04 062937](https://github.com/kingwingfly/fav/assets/107339377/679ae0f6-a8f1-49d9-af38-e8103ea856eb)

**Information (please complete the following information):**
Microsoft Windows 11
Build 22621.ni_release.220506_1250

**Additional context**
另外还有一个问题，它的下载速度总是随时间递减至零，导致每次都下不完需要反复执行。可以优化吗？还是b站服务器做了流量限制？

**Comment by feiudfyg** [comment]
注：已经经历三次崩溃，输出相同，个人认为可视为同一bug导致

**Comment by kingwingfly** [comment]
原因：没有办法调用 ffmpeg （不是 ffmpeg 返回错误，而是无法调用它）。

他宝贝的，真奇怪🤔

**Comment by kingwingfly** [comment]
初步怀疑是 ffmpeg 同时写了同一个文件，因为那里确实存在潜在的竞态条件。

目前，合并时，先检查同名文件，再合并，若同名，则加上 bvid。如果两个线程同时检查，都得出不存在，然后同时写同一个文件，就寄了。

**Comment by feiudfyg** [comment]
谢谢解答。这个issue是否应该暂时保留？我可以提供测试。另外还有好多问题TAT

**Comment by feiudfyg** [comment]
[fav.exe.7832.dmp](https://github.com/user-attachments/files/15552607/fav.exe.7832.dmp)
[fav.exe.8036.dmp](https://github.com/user-attachments/files/15552608/fav.exe.8036.dmp)
[fav.exe.16568.dmp](https://github.com/user-attachments/files/15552609/fav.exe.16568.dmp)
memory dumps

**Comment by kingwingfly** [comment]
解决了调用 ffmpeg 时可能的竞态条件。若没有在出现，则认为该 bug 已修复。

**Comment by feiudfyg** [comment]
目前没有大量任务，暂时没有测试条件。
偶尔下载一两个任务不会报错，可以认为已经修复。
