### ISSUE TITLE
[Bug] Weird display behavior

### ISSUE THREAD

**Issue by feiudfyg** [kingwingfly/fav#77]
**Describe the bug**
1.进行下载操作时的报错信息会被更新下载进度的屏幕重绘给覆盖掉，导致报错一闪而过就没了，翻回去也没有
这极大影响了bug汇报
2.下载久了整个终端里的文字都会狂闪，更新一遍就闪一次，看不到一点

**To Reproduce**
1. perform download command.
2. focus on the output, seek for any ERROR or WARNING and flashing screen.
3. notice that when the terminator redraw its display, the error messages disappear.

**Expected behavior**
any output are preserved for users to see and debug.

**Screenshots**
since the error messages disappears instantly, there is no method to create valid screnshots.

**Information (please complete the following information):**
OS: win11 22621

**Additional context**
Is it intended? or bug? i think this problem really prevents the users to report potential bugs.

**Comment by kingwingfly** [comment]
window 不知道，Linux 可以使用重定向符

`fav pull 2> log` 把标准错误重定向。

**Comment by feiudfyg** [comment]
Windows好像有1 > log.txt把标准错误流重定向。我去试试
不过现在因为别的错误太猛了 搞得这个bug都没法复现了

**Comment by kingwingfly** [comment]
The title of will be aligned better. 

Log will be write to `stdout`, and processbar to `stderr` now (v0.2.22).

Now, run
```
fav pull > log
```
to record log. 

If no mess in one week, I'll close this issue.

**Comment by feiudfyg** [comment]
暂时没有需要大量下载的情况，没办法妥善测试。
少量下载不会产生问题。可认为已经修复。
