### ISSUE TITLE
[Bug] Download record wont be saved when any error occurs

### ISSUE THREAD

**Issue by feiudfyg** [kingwingfly/fav#78]
**Describe the bug**
如果程序未正常退出(ctrl^c ,crash,freeze,taskmgr...)下一次pull将下载上次应当下载的所有文件，包括上次已经完整下载的文件。

**To Reproduce**
1.下载
2.等待bug导致崩溃
3.关闭窗口，重新运行fav pull
4.发现程序试图下载上次已经完整保存的文件。

**Expected behavior**
任何已经下载完整的文件立刻被写入sets文件，无论如何退出都不会被再次下载

**Screenshots**
N/A

**Information (please complete the following information):**
OS: win11 22621

**Additional context**
none

**Comment by feiudfyg** [comment]
作者辛苦了。

**Comment by kingwingfly** [comment]
这不可能啊...至少 ctrl c 不该有问题

**Comment by feiudfyg** [comment]
我也觉得不可能啊 这个issue我好像似曾相识
待会我再测试一下 监控下磁盘写入 看看具体到底是什么行为

**Comment by kingwingfly** [comment]
你还可以瞧瞧缓存有没有自动清理，如果那么多 bug 的话。

缓存位置通过
```powershell
GetTempPath
```
得到

**Comment by kingwingfly** [comment]
重构修复
