### ISSUE TITLE
[Bug] `fav pull` bug collection

### ISSUE THREAD

**Issue by kingwingfly** [kingwingfly/fav#79]
**Describe the bug**
1. ctrl-c not handled
2. error hints mess progress bar
3. unknown network error
4. sets not saved if quit

**Comment by kingwingfly** [comment]
- [x] #75 
- [x]  #76
- [x] #77 
- [x] #78

**Comment by kingwingfly** [comment]
@Silicon7921

If bug fixed after v0.2.20, let me know here, thanks a lot!

**Comment by feiudfyg** [comment]
seems fixed properly. thank you.
